CREATE TABLE `activityLog` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`entityType` varchar(50) NOT NULL,
	`entityId` int NOT NULL,
	`action` enum('create','update','delete','view','export','import','approve','reject') NOT NULL,
	`description` text,
	`previousData` json,
	`newData` json,
	`ipAddress` varchar(45),
	`userAgent` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `activityLog_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `assessmentComponents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`code` varchar(50) NOT NULL,
	`category` enum('structural','exterior','roofing','plumbing','electrical','hvac','interior','fire_safety','accessibility','site','other') NOT NULL,
	`description` text,
	`expectedLifespan` int,
	`weight` decimal(5,4) DEFAULT '1.0000',
	`sortOrder` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `assessmentComponents_id` PRIMARY KEY(`id`),
	CONSTRAINT `assessmentComponents_code_unique` UNIQUE(`code`)
);
--> statement-breakpoint
CREATE TABLE `assessments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`assetId` int NOT NULL,
	`componentId` int NOT NULL,
	`assessorId` int,
	`assessmentDate` timestamp NOT NULL,
	`conditionRating` enum('1','2','3','4','5') NOT NULL,
	`conditionNotes` text,
	`deficiencyDescription` text,
	`deficiencySeverity` enum('minor','moderate','major','critical'),
	`recommendedAction` enum('none','monitor','preventive_maintenance','repair','replace','immediate_action') DEFAULT 'none',
	`estimatedRepairCost` decimal(12,2),
	`priorityLevel` enum('1','2','3','4','5') DEFAULT '3',
	`remainingLifeYears` int,
	`quantity` decimal(10,2),
	`unit` varchar(50),
	`location` varchar(255),
	`accessibilityIssue` boolean DEFAULT false,
	`safetyHazard` boolean DEFAULT false,
	`energyEfficiencyIssue` boolean DEFAULT false,
	`codeViolation` boolean DEFAULT false,
	`status` enum('draft','submitted','reviewed','approved','rejected') DEFAULT 'draft',
	`reviewedById` int,
	`reviewedAt` timestamp,
	`reviewNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `assessments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `assetCategories` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`code` varchar(50) NOT NULL,
	`description` text,
	`icon` varchar(100),
	`color` varchar(20),
	`parentId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `assetCategories_id` PRIMARY KEY(`id`),
	CONSTRAINT `assetCategories_code_unique` UNIQUE(`code`)
);
--> statement-breakpoint
CREATE TABLE `assets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`categoryId` int,
	`name` varchar(255) NOT NULL,
	`assetCode` varchar(100) NOT NULL,
	`description` text,
	`address` text,
	`latitude` decimal(10,8),
	`longitude` decimal(11,8),
	`yearBuilt` int,
	`yearRenovated` int,
	`squareFootage` decimal(12,2),
	`numberOfFloors` int,
	`numberOfUnits` int,
	`occupancyType` enum('occupied','vacant','partially_occupied','seasonal') DEFAULT 'occupied',
	`ownershipType` enum('municipal','state','federal','private','mixed') DEFAULT 'municipal',
	`constructionType` varchar(100),
	`primaryUse` varchar(255),
	`secondaryUse` varchar(255),
	`replacementValue` decimal(15,2),
	`insuranceValue` decimal(15,2),
	`annualMaintenanceCost` decimal(12,2),
	`lastInspectionDate` timestamp,
	`nextInspectionDate` timestamp,
	`status` enum('active','inactive','pending_demolition','under_construction','renovating') DEFAULT 'active',
	`overallCondition` enum('excellent','good','fair','poor','critical'),
	`fciScore` decimal(5,4),
	`metadata` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `assets_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `capitalProjects` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`assetId` int,
	`name` varchar(255) NOT NULL,
	`description` text,
	`scope` text,
	`justification` text,
	`estimatedCost` decimal(15,2),
	`costConfidenceLevel` enum('low','medium','high') DEFAULT 'medium',
	`priority` enum('1','2','3','4','5') DEFAULT '3',
	`category` enum('safety','code_compliance','deferred_maintenance','energy_efficiency','accessibility','capacity','modernization','replacement','other') DEFAULT 'other',
	`recommendedYear` int,
	`estimatedDuration` int,
	`fundingSource` varchar(255),
	`status` enum('proposed','approved','funded','in_progress','completed','deferred','cancelled') DEFAULT 'proposed',
	`relatedAssessmentIds` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `capitalProjects_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `comments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`entityType` enum('asset','assessment','project','capital_project') NOT NULL,
	`entityId` int NOT NULL,
	`parentId` int,
	`content` text NOT NULL,
	`isResolved` boolean DEFAULT false,
	`resolvedById` int,
	`resolvedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `comments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `documents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int,
	`assetId` int,
	`name` varchar(255) NOT NULL,
	`description` text,
	`url` varchar(500) NOT NULL,
	`fileSize` int,
	`mimeType` varchar(100),
	`documentType` enum('report','drawing','specification','permit','warranty','maintenance_record','inspection_report','cost_estimate','other') DEFAULT 'other',
	`version` varchar(50),
	`uploadedById` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `documents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `municipalities` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`code` varchar(50) NOT NULL,
	`state` varchar(100),
	`country` varchar(100) DEFAULT 'USA',
	`population` int,
	`area` decimal(10,2),
	`contactEmail` varchar(320),
	`contactPhone` varchar(50),
	`address` text,
	`website` varchar(500),
	`logoUrl` varchar(500),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `municipalities_id` PRIMARY KEY(`id`),
	CONSTRAINT `municipalities_code_unique` UNIQUE(`code`)
);
--> statement-breakpoint
CREATE TABLE `photos` (
	`id` int AUTO_INCREMENT NOT NULL,
	`assessmentId` int,
	`assetId` int,
	`url` varchar(500) NOT NULL,
	`thumbnailUrl` varchar(500),
	`filename` varchar(255),
	`fileSize` int,
	`mimeType` varchar(100),
	`caption` text,
	`photoType` enum('exterior','interior','deficiency','before','after','overview','detail','other') DEFAULT 'other',
	`takenAt` timestamp,
	`takenById` int,
	`latitude` decimal(10,8),
	`longitude` decimal(11,8),
	`sortOrder` int DEFAULT 0,
	`isPrimary` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `photos_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `projects` (
	`id` int AUTO_INCREMENT NOT NULL,
	`municipalityId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`projectNumber` varchar(100) NOT NULL,
	`status` enum('draft','in_progress','under_review','completed','archived') NOT NULL DEFAULT 'draft',
	`priority` enum('low','medium','high','critical') DEFAULT 'medium',
	`startDate` timestamp,
	`endDate` timestamp,
	`dueDate` timestamp,
	`budget` decimal(15,2),
	`actualCost` decimal(15,2),
	`projectManagerId` int,
	`clientContact` varchar(255),
	`clientEmail` varchar(320),
	`clientPhone` varchar(50),
	`notes` text,
	`tags` json,
	`createdById` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `projects_id` PRIMARY KEY(`id`),
	CONSTRAINT `projects_projectNumber_unique` UNIQUE(`projectNumber`)
);
--> statement-breakpoint
CREATE TABLE `users` (
	`id` int AUTO_INCREMENT NOT NULL,
	`openId` varchar(64) NOT NULL,
	`name` text,
	`email` varchar(320),
	`loginMethod` varchar(64),
	`role` enum('user','admin') NOT NULL DEFAULT 'user',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`lastSignedIn` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `users_id` PRIMARY KEY(`id`),
	CONSTRAINT `users_openId_unique` UNIQUE(`openId`)
);
