CREATE TABLE `cof_factors` (
	`id` int AUTO_INCREMENT NOT NULL,
	`riskAssessmentId` int NOT NULL,
	`safetyImpact` decimal(3,2) NOT NULL,
	`safetyNotes` text,
	`operationalImpact` decimal(3,2) NOT NULL,
	`downtimeDays` decimal(5,1),
	`affectedSystems` text,
	`operationalNotes` text,
	`financialImpact` decimal(3,2) NOT NULL,
	`repairCost` decimal(15,2),
	`revenueLoss` decimal(15,2),
	`penaltyCost` decimal(15,2),
	`financialNotes` text,
	`environmentalImpact` decimal(3,2) NOT NULL,
	`environmentalNotes` text,
	`reputationalImpact` decimal(3,2) NOT NULL,
	`reputationalNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cof_factors_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `critical_equipment` (
	`id` int AUTO_INCREMENT NOT NULL,
	`assessmentId` int NOT NULL,
	`criticalityLevel` enum('critical','important','standard') NOT NULL,
	`criticalityJustification` text,
	`isSafetyRelated` int DEFAULT 0,
	`isMissionCritical` int DEFAULT 0,
	`isHighValue` int DEFAULT 0,
	`hasRedundancy` int DEFAULT 0,
	`mitigationStrategies` text,
	`contingencyPlan` text,
	`designatedBy` int NOT NULL,
	`designatedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `critical_equipment_id` PRIMARY KEY(`id`),
	CONSTRAINT `critical_equipment_assessmentId_unique` UNIQUE(`assessmentId`)
);
--> statement-breakpoint
CREATE TABLE `pof_factors` (
	`id` int AUTO_INCREMENT NOT NULL,
	`riskAssessmentId` int NOT NULL,
	`age` int,
	`expectedUsefulLife` int,
	`remainingLifePercent` decimal(5,2),
	`conditionIndex` decimal(5,2),
	`defectSeverity` enum('none','minor','moderate','major','critical'),
	`maintenanceFrequency` enum('none','reactive','scheduled','preventive','predictive'),
	`lastMaintenanceDate` timestamp,
	`deferredMaintenanceYears` int,
	`operatingEnvironment` enum('controlled','normal','harsh','extreme'),
	`utilizationRate` decimal(5,2),
	`equipmentType` varchar(100),
	`manufacturer` varchar(255),
	`model` varchar(255),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `pof_factors_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `risk_assessments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`assessmentId` int NOT NULL,
	`pof` decimal(3,2) NOT NULL,
	`pofJustification` text,
	`cof` decimal(3,2) NOT NULL,
	`cofJustification` text,
	`riskScore` decimal(5,2) NOT NULL,
	`riskLevel` enum('very_low','low','medium','high','critical') NOT NULL,
	`assessedBy` int NOT NULL,
	`assessedAt` timestamp NOT NULL DEFAULT (now()),
	`reviewedBy` int,
	`reviewedAt` timestamp,
	`status` enum('draft','approved','archived') NOT NULL DEFAULT 'draft',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `risk_assessments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `risk_mitigation_actions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`riskAssessmentId` int NOT NULL,
	`action` text NOT NULL,
	`actionType` enum('inspection','maintenance','repair','replacement','monitoring','procedure_change','training') NOT NULL,
	`priority` enum('immediate','high','medium','low') NOT NULL,
	`status` enum('planned','in_progress','completed','cancelled') NOT NULL DEFAULT 'planned',
	`assignedTo` int,
	`dueDate` timestamp,
	`completedDate` timestamp,
	`estimatedCost` decimal(15,2),
	`actualCost` decimal(15,2),
	`expectedRiskReduction` decimal(5,2),
	`actualRiskReduction` decimal(5,2),
	`effectiveness` enum('not_effective','partially_effective','effective','highly_effective'),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `risk_mitigation_actions_id` PRIMARY KEY(`id`)
);
