CREATE TABLE `maintenance_entries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`assessmentId` int,
	`componentName` varchar(255) NOT NULL,
	`location` varchar(255),
	`entryType` enum('identified','executed') NOT NULL,
	`actionType` enum('repair','rehabilitation','replacement','preventive_maintenance','emergency_repair','inspection','upgrade') NOT NULL,
	`lifecycleStage` enum('installation','routine_maintenance','major_repair','replacement','decommission'),
	`description` text NOT NULL,
	`workPerformed` text,
	`findings` text,
	`estimatedCost` decimal(15,2),
	`actualCost` decimal(15,2),
	`costVariance` decimal(15,2),
	`costVariancePercent` decimal(5,2),
	`status` enum('planned','approved','in_progress','completed','deferred','cancelled') NOT NULL DEFAULT 'planned',
	`priority` enum('immediate','high','medium','low') NOT NULL DEFAULT 'medium',
	`dateIdentified` timestamp,
	`dateScheduled` timestamp,
	`dateStarted` timestamp,
	`dateCompleted` timestamp,
	`isRecurring` boolean NOT NULL DEFAULT false,
	`recurringFrequency` enum('weekly','monthly','quarterly','semi_annual','annual','biennial'),
	`nextDueDate` timestamp,
	`lastCompletedDate` timestamp,
	`contractor` varchar(255),
	`contractorContact` varchar(255),
	`warrantyExpiry` timestamp,
	`componentAge` int,
	`cumulativeCost` decimal(15,2),
	`notes` text,
	`attachments` json,
	`createdBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `maintenance_entries_id` PRIMARY KEY(`id`)
);
